### PR TITLE
Synch MSFT changes

### PR DESCRIPTION
**Pull request by mafaldag1**

### CODE REVIEW

**Comment by jankrassnigg** [comment]
@mafaldag1 any reason to keep this a draft ?

**Comment by mafaldag1** [comment]
@jankrassnigg sorry! we would like to add one more change related to Frustum. will update the PR asap

**Comment by jankrassnigg** [comment]
Okay, just wanted to know whether this is on purpose.

**Comment by jankrassnigg** [comment]
Any update on this?

**Comment by mafaldag1** [comment]
@jankrassnigg still polishing some details on the change! will update the PR as soon as it's done

**Pull request merged**
