### PR TITLE
Fix remaining PVS-Studio performance related issues in Foundation and Core

### PR DESCRIPTION
**Pull request by dimhotepus**
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/

### CODE REVIEW

**Comment by dimhotepus** [comment]
@jankrassnigg Unable to find out why Clang-Tidy complains:

```
Formatted command: . 'D:\a\1\s\Utilities\RunClangTidy.ps1' -DiffTo "origin/dev" -LlvmInstallDir "$pwd\llvm" -Workspace "workspace-clang"
2023-05-18T07:21:45.3854738Z ========================== Starting Command Output ===========================
2023-05-18T07:21:45.4070086Z ##[command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\c0632cc6-ac1d-4814-b7b9-d893b2aa8544.ps1'"
2023-05-18T07:21:45.9041094Z Clang include path D:\a\1\s\llvm\lib\clang\15.0.3\include
2023-05-18T07:21:45.9148550Z Temporary Directory is C:\Users\VssAdministrator\AppData\Local\Temp\093d7c93-976d-4908-a40d-b6eb6064f930
2023-05-18T07:21:47.4329214Z D:\a\1\s\Utilities\RunClangTidy.ps1 : Git merge-base failed: 
2023-05-18T07:21:47.4331246Z At D:\a\_temp\c0632cc6-ac1d-4814-b7b9-d893b2aa8544.ps1:4 char:1
2023-05-18T07:21:47.4344203Z + . 'D:\a\1\s\Utilities\RunClangTidy.ps1' -DiffTo "origin/dev" -LlvmIns …
2023-05-18T07:21:47.4345115Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-05-18T07:21:47.4345829Z + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2023-05-18T07:21:47.4346363Z + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RunClangTidy.ps1
2023-05-18T07:21:47.6489592Z ##[error]PowerShell exited with code '1'
```

**Comment by jankrassnigg** [comment]
> @jankrassnigg Unable to find out why Clang-Tidy complains:
> 
> ```
> Formatted command: . 'D:\a\1\s\Utilities\RunClangTidy.ps1' -DiffTo "origin/dev" -LlvmInstallDir "$pwd\llvm" -Workspace "workspace-clang"
> 2023-05-18T07:21:45.3854738Z ========================== Starting Command Output ===========================
> 2023-05-18T07:21:45.4070086Z ##[command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\c0632cc6-ac1d-4814-b7b9-d893b2aa8544.ps1'"
> 2023-05-18T07:21:45.9041094Z Clang include path D:\a\1\s\llvm\lib\clang\15.0.3\include
> 2023-05-18T07:21:45.9148550Z Temporary Directory is C:\Users\VssAdministrator\AppData\Local\Temp\093d7c93-976d-4908-a40d-b6eb6064f930
> 2023-05-18T07:21:47.4329214Z D:\a\1\s\Utilities\RunClangTidy.ps1 : Git merge-base failed: 
> 2023-05-18T07:21:47.4331246Z At D:\a\_temp\c0632cc6-ac1d-4814-b7b9-d893b2aa8544.ps1:4 char:1
> 2023-05-18T07:21:47.4344203Z + . 'D:\a\1\s\Utilities\RunClangTidy.ps1' -DiffTo "origin/dev" -LlvmIns …
> 2023-05-18T07:21:47.4345115Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2023-05-18T07:21:47.4345829Z + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
> 2023-05-18T07:21:47.4346363Z + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RunClangTidy.ps1
> 2023-05-18T07:21:47.6489592Z ##[error]PowerShell exited with code '1'
> ```

That's normal for PRs from forked repositories. Can be ignored.

**Pull request merged**
