### PR TITLE
Removal of zlib

### PR DESCRIPTION
**Pull request by ArshErgon**
Issue #638 
Summary:
`Code/ThirdParty/zlib` has been removed
Checked `CMakeLists.txt ` couldn't find `EZ_3RDPARTY_ZLIB_SUPPORT`
Check `.cmake` files, found one potential match removed.
Removed `BUILDSYSTEM_ENABLE_ZLIB_SUPPORT` 
Removed `CompressedStreamZlib.h`
Have run CMake on `CMakeList.txt` complied fully
* Updated and formatted `Readme.md` and `Contribution.md`
Thank you.

### CODE REVIEW

**Review by jankrassnigg — APPROVED** [review]
Looks good, thanks a lot! :-)

**Comment by jankrassnigg** [comment]
I'll merge the PR once the build pipelines are done. "Closing" the PR means abandoning it, that's not what you want.

**Comment by ArshErgon** [comment]
@jankrassnigg sorry, I'm new to this, will keep this in mind.
Thanks for the approval

**Pull request merged**
