### PR TITLE
Enable EditorEngineProcess callstack printing & make it clickable

### PR DESCRIPTION
**Pull request by RiederAlex**
This implements #1210 for windows

- Enabled crash handler for EditorEngineProcess
- Added ability to configure a code editor in Preferences -> Application: C++ Projects
- Double clicking a stacktrace in the engine log now launches the configured editor, showing the file/line parsed from the stacktrace.

### CODE REVIEW

**Comment by jankrassnigg** [comment]
What would be a way to test this? When I add an assert into a component in the Monster Attack sample, I get the assert message in the log, but no callstack.

Also what editor + arguments are you using for testing? We already have the C++ IDE setting, why don't we just use that?

**Comment by RiederAlex** [comment]
I tested it like this in my component's Update(): `int* bla = nullptr; *bla = 5;`
adding an assert like `EZ_ASSERT_DEV(false,"Assert!");` in the same place also triggered a callstack for me in **Dev** configuration.

However I just noticed that in **Debug** when the "Debug Assertion Failed" message pops up one has to press "Retry" for it to produce a stacktrace. I'll add support for double clicking the initial assert message as well, should be easy enough.

For testing/developing I use Clion, but from quickly checking most code editors support some kind of "open file and jump to line" CLI command, here are some examples I could test with the stuff I had installed:

- Clion: `clion64.exe {file} --line {line}`
- Sublime: `sublime_text.exe {file}:{line}`
- VSCode: `code.exe -g {file}:{line}`
- VisualStudio unfortunately is very special and would require custom code/scripts, as it does not expose "open file and jump to line" via CLI (See [this StackOverflow post](https://stackoverflow.com/questions/350323/open-a-file-in-visual-studio-at-a-specific-line-number) for possible solutions)

**Why are we not using the C++ IDE Settings?**
I've looked at this setting for my initial approach (`ezCppProject::ezIDE`) but came to the conclusion that it does not fit the needs of this feature right now, as it does not expose the editor binary directly and does not allow configuring custom editors - something which I find very important, as one cannot possibly support all of them out of the box :)

However - usability wise I agree that this would be a better choice from a user perspective, having one setting instead of two.
What I could do (if this is still in the scope of the PR):
  - Add another IDE (calling it 'Custom') so we do not loose the "I have my own esoteric code editor" usecase.
  - Figure out the path for supported editors automatically (similar to what happens in `ezQtUiServices::OpenInVsCode()`). This would mean adding extra code to support/find different VisualStudio installations and letting the user select a specific one.
  - Auto-fill m_sEditorPath/m_sEditorArgs if a supported editor is selected (making these fields read-only/hide them).
  - Let the user manually fill out these fields if IDE is set to "Custom"
  
Is this something I should do in this PR or do you want me to create a new one after this one is accepted?

**Comment by jankrassnigg** [comment]
We can keep these as separate options. Because we only support certain compilers, but may want to allow users to use different text editors, also for other use cases in the future.
What would be nice, though, is a drop down with a few editors that are Auto detected, and for which we know the command lines. And one option would be custom, which then shows the two fields that we have now.

Whether you want to add this, at all, in this PR or in a follow up PR, I'll leave up to you.

**Comment by RiederAlex** [comment]
I'll try to get some version of auto-detection working in this PR - especially now that I've realized special handling is needed as VS is not exposing what I would have expected via its CLI.

**Comment by RiederAlex** [comment]
I've now added support for double clicking assert messages and for using VisualStudio as a code editor on Windows.

It now looks like this if VisualStudio is selected (default on Windows):
image

And it looks like this if a custom editor is configured:
image

VisualStudio support was a bit tricky to get working correctly - it now uses a script (Utilities\Scripts\open-in-msvs.vbs) in order to open up the latest installed VisualStudio and jump to the file/line. This might seem a bit odd, but it was required as VS does not expose a CLI to do that consistently. I chose this approach as it avoids doing a bunch of COM Interface stuff in C++ directly.

**Comment by RiederAlex** [comment]
I've fixed the Linux compile error, but Clang-Tidy seems to have some other problem unrelated to these changes.
Also seems like ClangFormat is not re-run automatically - it still reports issues which should be fixed with a6485da6a8199d4c927af07832690e7542386a63

**Comment by jankrassnigg** [comment]
I think I fixed the clang-tidy issue in the mean time.
Don't know about clang-format, it can't properly run on forked repos, that was always a problem. @Ingrater fixed some of that, but it looks like it's still not fully working.

**Comment by Sanakan8472** [comment]
So due to access restrictions, clang format can't apply formatting changes on forked repos, here is the error message:
```
This PR comes from the forked repository 'RiederAlex/ezEngine'
Formatting changes can't be applied automatically.
Please download the attached patch file and apply it manually using:
git apply -p0 clangFormat.patch
You can also run ClangFormat on the necessary files (see patch) from within Visual Studio.
Error: Process completed with exit code 1.
```
So @RiederAlex, can you please download the generated [ClangFormatPatch](https://github.com/ezEngine/ezEngine/actions/runs/8333352095/artifacts/1336679132) and apply it to your branch? Thanks!

**Comment by RiederAlex** [comment]
> So due to access restrictions, clang format can't apply formatting changes on forked repos, here is the error message:
> 
> ```
> This PR comes from the forked repository 'RiederAlex/ezEngine'
> Formatting changes can't be applied automatically.
> Please download the attached patch file and apply it manually using:
> git apply -p0 clangFormat.patch
> You can also run ClangFormat on the necessary files (see patch) from within Visual Studio.
> Error: Process completed with exit code 1.
> ```
> 
> So @RiederAlex, can you please download the generated [ClangFormatPatch](https://github.com/ezEngine/ezEngine/actions/runs/8333352095/artifacts/1336679132) and apply it to your branch? Thanks!

I've already did that in a force push in a6485da6a8199d4c927af07832690e7542386a63 - thats why I said that unfortunately it seems like the clang-format job does not re-run with my latest changes (maybe it does not like force pushes?).

I'm a bit lost on how I should trigger this job again from my side.

**Comment by jankrassnigg** [comment]
Ah sorry, forgot about this PR. I don't think the clang-format stuff is important, I see you applied the changes, so I guess the rest is a bug in our system.
Is this good to go in now? Then I'll just submit it.

**Comment by RiederAlex** [comment]
Yes - the only thing that I'm a bit unsure about is the location I've put the required .vbs script (see reasoning [here](https://github.com/ezEngine/ezEngine/pull/1232#issuecomment-2002101387)) and for the moment it looks a bit strange, as both "C++ IDE" and "Code Editor Preferences" can be configured, which might confuse users.

If you think both of these are acceptable then go ahead and submit it :)

**Comment by jankrassnigg** [comment]
I don't really have time to test this in detail atm, so I'll just close the PR and then we can polish things as we notice them over time.

**Pull request merged**
