### PR TITLE
Editor Preference to Clear Editor Log on Play

### PR DESCRIPTION
**Pull request by neilmewada**
Added Editor Preference boolean to Clear Editor Logs on Play. https://github.com/ezEngine/ezEngine/issues/628

### CODE REVIEW

**Comment by jankrassnigg** [comment]
Thank you for the contribution. Looks good from a rough glance, I'll take a closer look probably tomorrow.

**Comment by neilmewada** [comment]
Thanks @jankrassnigg! Looking forward to contributing to this project further 👍

**Review by jankrassnigg — APPROVED** [review]
Looks good, thanks a lot!

**Pull request merged**
