### PR TITLE
Fixed type conversion warnings

### PR DESCRIPTION
**Pull request by C-Core**
and enabled the warning again in the build settings

### CODE REVIEW

**Comment by C-Core** [comment]
@jankrassnigg The typescript plugin converts a component handle to an uint32 although a component handle is 64bit, this doesn't seem to be correct?

E.g.
C:\Source\ezEngine\Code\EnginePlugins\TypeScriptPlugin\TsBinding\TsComponent.cpp(111): warning C4244: 'initializing': conversion from 'ezComponentId::StorageType' to 'ezUInt32', possible loss of data (compiling source file C:\Source\ezEngine\Workspace\Win64\Code\EnginePlugins\TypeScriptPlugin\TsBinding\unity_6905569600eebe6ba989059ef60dbe1195557b23.cpp)

**Comment by jankrassnigg** [comment]
> @jankrassnigg The typescript plugin converts a component handle to an uint32 although a component handle is 64bit, this doesn't seem to be correct?

Yes, looks fishy. It works, because nobody calls that function :D There is a pointer overload for that function, which does something entirely different, and that is used everywhere. Probably some left-over from the early development phase.

Can you just remove that function in your change?

**Comment by C-Core** [comment]
> Yes, looks fishy. It works, because nobody calls that function :D There is a pointer overload for that function, which does something entirely different, and that is used everywhere. Probably some left-over from the early development phase.
> 
> Can you just remove that function in your change?

I removed the function but the same problem exists in ezTypeScriptBinding::DeleteTsComponent. What should I do with this function? I can't remove it since it used in ezTypeScriptComponent::Deinitialize.

**Comment by jankrassnigg** [comment]
I checked that, it was dead code as well by now. We have a 'garbage collection' step to remove stuff and this call had no effect anymore.

I removed those functions in latest dev.

**Pull request merged**
