### PR TITLE
[WIP] Advanced Materials

### PR DESCRIPTION
**Pull request by PlasmaDev5**
_**Opened PR for early Feedback**_

Based on changes made in SparkStudios branch - https://github.com/SparkyStudios/ezEngine/tree/feature/rendering

TODO:
- Templates
- Material Graph Support
- Parallax Occlusion Mapping
- Stochastic Texturing (Hex Sampling)

## Overview

Added permutation to switch between new shading and old shading
Added permutation to switch diffuse model 4 options to pick from (changes minor but may give a preferred look, my project uses chan)

### **Anisotropic Materials:**
Anisotropic - How anisotropic the specular is.
Anisotropic  Rotation - direction of the anisotropy
Anisotropic Texture - Red = Anisotropic, Green = Rotation
image

### **Clearcoat Materials:**
Clearcoat - Blends into the clearcoat effect
Clearcoat Roughness - Roughness of the clearcoat layer
ClearcoatTexture - RG = Normal, B = Roughness, A = Clearcoat
image

### **SheenMaterials:**
Sheen - Strength of the effect
Sheen Tint - 0 = White sheen, 1 = Diffuse Color
Sheen Texture - R = Sheen, G = Tint 
image

### CODE REVIEW

**Comment by PlasmaDev5** [comment]
Note: this is on temporary hold due to focus on features that are more important for my current needs

**Comment by jankrassnigg** [comment]
Any progress on this? Otherwise I'll just close the PR now.

**Comment by PlasmaDev5** [comment]
Not had much progress on this currently due to work commitments. Will hopefully get back to it soon. As part of it i will also look to backport the transparency roughness blur effect and possibly some more if done in time.
image

**Comment by PlasmaDev5** [comment]
closing as i have not had much time to work on it. Will open in a separate reworked pr in the future

**Pull request closed without merging**
