### PR TITLE
PVS-Studio fixes for GameEngine

### PR DESCRIPTION
**Pull request by dimhotepus**
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/

### CODE REVIEW

**Review by jankrassnigg — APPROVED** [review]

**Comment by dimhotepus** [comment]
@jankrassnigg Could we rerun the pipeline?

**Comment by Ingrater** [comment]
@dimhotepus in order for the clang-tidy check to pass you will need to rebase your PR to latest dev.

**Comment by dimhotepus** [comment]
@Ingrater Done.

**Comment by dimhotepus** [comment]
@ingrater Looks like some problems with PowerShell script to run Clang-Tidy on PRs.

```
Clang include path D:\a\1\s\llvm\lib\clang\15.0.3\include
Temporary Directory is C:\Users\VssAdministrator\AppData\Local\Temp\1b752b2a-6f65-4880-8573-236d69a3eaf1
D:\a\1\s\Utilities\RunClangTidy.ps1 : Git merge-base failed: 
At D:\a\_temp\73654d39-77cb-45d1-b958-7fd425d820c3.ps1:4 char:1
+ . 'D:\a\1\s\Utilities\RunClangTidy.ps1' -DiffTo "origin/dev" -LlvmIns …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RunClangTidy.ps1
```

**Comment by Ingrater** [comment]
@dimhotepus yeah the cang-tidy check seems to have an issue. I'll look at that some other time.

**Pull request merged**
